// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uzoqlvtkgiaarhcqfegm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV6b3FsdnRrZ2lhYXJoY3FmZWdtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMjMwNTcsImV4cCI6MjA1OTY5OTA1N30.ZbL3Wx5M2n8w4pxkfc88zKPHZKM9vsKCj3RVtVhXWzA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);